### ISSUE TITLE
Getting this up and running

### ISSUE THREAD

**Issue by EdwardDeaver** [wojciechp6/YOLOv8Unity#1]
Hi, I am looking to run this in my Unity project.

How do you recommend on adding this to a project?

**Comment by wojciechp6** [comment]
Hello, I will update today the readme file to explain how to run this project. Stay in tune!

**Comment by wojciechp6** [comment]
I did some refactoring and updated the readme file with instructions on the usage of this project. If you still have some questions, feel free to ask me. 

Coming back to your question. You need to copy all of the scripts and write your scenario of usage. For now, the only MonoBehaviour script is *WebCamDetector.cs*. You can use it as an example of how to run the model and use the results. 

If you still have questions, feel free to ask.
Good luck!
