### ISSUE TITLE
Model not visible in the Unity assets

### ISSUE THREAD

**Issue by rawatsaurabh** [wojciechp6/YOLOv8Unity#5]
Hello , 
I copied the models in the Asset folder,I can see them as well. I tried re-importing them and i can see them in the unity  but i cant see them when i tried to select them from the inspector windows infront of the Model File.
I am on 2022.3.20.f1 Unity 
![image](https://github.com/wojciechp6/YOLOv8Unity/assets/8255773/49accb1e-e045-4fb7-99cd-bd72b737debb)

![image](https://github.com/wojciechp6/YOLOv8Unity/assets/8255773/4abec60d-1ba5-4066-96af-2bb3ce571322)
As you can see in the new popped up window theres is no models in the Asset .I also retied creating a folder inside Asset Model)and putting the model inside it.
please let me know what i missed

**Comment by wojciechp6** [comment]
Hello!
How did you get these models? What are these models extensions? You need the onnx models to use with this project. 
You can get the onnx version of YOLOv8 from [PINTO model zoo](https://github.com/PINTO0309/PINTO_model_zoo/tree/main/345_YOLOv8) or generate it by yourself.

**Comment by rawatsaurabh** [comment]
yes I used the [PINTO model zoo](https://github.com/PINTO0309/PINTO_model_zoo/tree/main/345_YOLOv8) only. I ran the downoad.sh script and then untarred the resources.tar and then inside this folder resources.tar\yolov8_n_seg i copied both model_float16.tflite , model_float32.tflite   and saved_model.pb in the assets. is it correct?

**Comment by wojciechp6** [comment]
Hello. No, it isn't correct. You need to copy models with the ***.onnx*** extension.  You will find it in the PINTO archive main folder.
