### ISSUE TITLE
onnx model import issue

### ISSUE THREAD

**Issue by Miftahur92** [wojciechp6/YOLOv8Unity#7]
Hi, I am trying to import a .onnx model exported using YOLOv8. However, I am getting this following error.
OnnxImportException: Unexpected error while parsing layer /model.2/Split_output_0 of type Split.
Unsupported default attribute `split` for node /model.2/Split_output_0 of type Split. Value is required.

Are you using any specific version of Barracuda?

**Comment by wojciechp6** [comment]
Hey!

This project uses Barracuda 3.0.0.
You can try this [notebook](https://colab.research.google.com/drive/1YjSQ0IJvKimrc5-I4QXaWJ43-nbPqKOS?usp=sharing) to fix the onnx model.
