### ISSUE TITLE
yolo-pose

### ISSUE THREAD

**Issue by AccSSS** [wojciechp6/YOLOv8Unity#8]
Hi, this project is amazing. It allows me to learn how to use yolov8 in unity. Now I have a question, how should I use yolo-pose? Can you give me some ideas or code? Thank you very much.

**Comment by wojciechp6** [comment]
Hello, thanks for your kind words. 

You can use yolo pose by creating new classes inheriting from YOLOv8OutputReader and YOLOv8. 
YOLO pose returns detections with 17 keypoints each, so create a new data class for results (inherit from ResultBox) and parse them in your new OutputReader class. Each keypoint has 3 parameters: x position, y position, and visibility (all three are floats). Then you can create a class that inherits from YOLOv8 class and use your OutputReader. The last part is to create a MonoBehaviour script that uses your new classes. It can inherit from the Detector script as the Segmentator does. 

You should inspire yourself how the segmentation is implemented and how it is built upon detection. 
If you need further support, feel free to write.
