### ISSUE TITLE
ModelZoo not found

### ISSUE THREAD

**Issue by Cr1mePenta** [wojciechp6/YOLOv8Unity#9]
Hey there,
I wanted to try your code but unfortunately the model zoo v8 pretrained model wasn't there anymore.
Do you have by chance a copy of that or do I need to create/train my own?

**Comment by wojciechp6** [comment]
Hello, you can easily export onnx version using [export command](https://docs.ultralytics.com/usage/cli/#export). 
You should also convert it for barracuda using [this notebook](https://colab.research.google.com/drive/1YjSQ0IJvKimrc5-I4QXaWJ43-nbPqKOS?usp=sharing).

**Comment by Cr1mePenta** [comment]
Oh nice thank you!
